name: Deploy to Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Astro
        run: |
          bun install && bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: dist/ 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
